#!/usr/bin/env python3
"""
RQ1: Does resource-stress injection (Shaker) detect more Python flaky tests
than plain re-execution (ReRun) at an equal execution budget?

Paired binary detection on the 137-test common set (budget-matched at 100
executions). Emits a contingency table + McNemar test, with a sensitivity
analysis that excludes tests whose runs were truncated (<100).
"""
from __future__ import annotations

from pathlib import Path

from analysis.load import load_paired
from analysis.stats_util import Prop, mcnemar_cc, mcnemar_exact

GEN = Path(__file__).resolve().parent.parent / "paper" / "generated"


def contingency(df):
    both = int((df.shaker_flaky & df.rerun_flaky).sum())
    s_only = int((df.shaker_flaky & ~df.rerun_flaky).sum())
    r_only = int((~df.shaker_flaky & df.rerun_flaky).sum())
    neither = int((~df.shaker_flaky & ~df.rerun_flaky).sum())
    return both, s_only, r_only, neither


def report(df, label):
    n = len(df)
    both, s_only, r_only, neither = contingency(df)
    shaker = Prop(both + s_only, n)
    rerun = Prop(both + r_only, n)
    either = Prop(both + s_only + r_only, n)
    p_exact = mcnemar_exact(s_only, r_only)
    chi2, p_cc = mcnemar_cc(s_only, r_only)
    print(f"\n=== RQ1 [{label}] n={n} ===")
    print(f"  both={both}  shaker_only={s_only}  rerun_only={r_only}  neither={neither}")
    print(f"  Shaker detect: {shaker.k}/{n} = {shaker.rate*100:.1f}%  CI={tuple(round(x*100,1) for x in shaker.ci)}")
    print(f"  ReRun  detect: {rerun.k}/{n} = {rerun.rate*100:.1f}%  CI={tuple(round(x*100,1) for x in rerun.ci)}")
    print(f"  Either detect: {either.k}/{n} = {either.rate*100:.1f}%")
    print(f"  McNemar exact two-sided p = {p_exact:.3f}")
    print(f"  McNemar chi^2 (cc) = {chi2:.3f}, p = {p_cc:.3f}")
    return dict(n=n, both=both, s_only=s_only, r_only=r_only, neither=neither,
                shaker=shaker, rerun=rerun, p_exact=p_exact)


def emit_tex(main, sens):
    GEN.mkdir(parents=True, exist_ok=True)
    m = main
    tex = rf"""% Auto-generated by analysis/rq1_shaker_vs_rerun.py -- do not edit by hand.
\begin{{table}}[t]
\centering
\begin{{tabular}}{{l c c c}}
\toprule
 & \textbf{{ReRun detects}} & \textbf{{ReRun misses}} & \textbf{{Total}} \\
\midrule
\textbf{{Shaker detects}} & {m['both']} & {m['s_only']} & {m['both']+m['s_only']} \\
\textbf{{Shaker misses}}  & {m['r_only']} & {m['neither']} & {m['r_only']+m['neither']} \\
\midrule
\textbf{{Total}}          & {m['both']+m['r_only']} & {m['s_only']+m['neither']} & {m['n']} \\
\bottomrule
\end{{tabular}}
\caption{{Paired detection outcomes for Shaker versus the budget-matched ReRun
baseline on the {m['n']} ground-truth flaky tests, 100 executions each. The
difference is not significant (McNemar exact $p = {m['p_exact']:.2f}$).}}
\label{{tab:rq1_contingency}}
\end{{table}}
"""
    (GEN / "tab_rq1_contingency.tex").write_text(tex)
    print(f"\nwrote {GEN / 'tab_rq1_contingency.tex'}")


def main():
    df = load_paired()
    main_res = report(df, "all 137")
    sens = report(df[~df.any_truncated], "no truncated")
    emit_tex(main_res, sens)


if __name__ == "__main__":
    main()
