#!/usr/bin/env python3
"""
RQ2: To what extent do known-flaky Python tests reproduce under repeated
execution on independent infrastructure?

Detection rate == recall against the Gruber ground truth (all analysed tests are
labelled flaky). Reports per-technique and combined ("either") recall with Wilson
CIs, and breaks down WHY the non-reproduced tests failed to manifest flakiness
(never flipped = all_passed; broken env = all_failed; possibly under-sampled =
truncated).
"""
from __future__ import annotations

from pathlib import Path

from analysis.load import load_paired
from analysis.stats_util import Prop

GEN = Path(__file__).resolve().parent.parent / "paper" / "generated"


def main():
    df = load_paired()
    n = len(df)
    shaker = Prop(int(df.shaker_flaky.sum()), n)
    rerun = Prop(int(df.rerun_flaky.sum()), n)
    either = Prop(int(df.either_flaky.sum()), n)

    not_repro = df[~df.either_flaky]
    # classify a non-reproduced test by its statuses across the two techniques
    def bucket(row):
        st = {row.shaker_status, row.rerun_status}
        if "all_failed" in st:
            return "all_failed (broken in env)"
        if row.any_truncated:
            return "truncated (under-sampled)"
        return "all_passed (never flipped)"

    buckets = not_repro.apply(bucket, axis=1).value_counts()

    print(f"\n=== RQ2 reproducibility (n={n}) ===")
    print(f"  Shaker recall: {shaker.k}/{n} = {shaker.rate*100:.1f}%  CI={tuple(round(x*100,1) for x in shaker.ci)}")
    print(f"  ReRun  recall: {rerun.k}/{n} = {rerun.rate*100:.1f}%  CI={tuple(round(x*100,1) for x in rerun.ci)}")
    print(f"  Either recall: {either.k}/{n} = {either.rate*100:.1f}%  CI={tuple(round(x*100,1) for x in either.ci)}")
    print(f"  Not reproduced by either: {len(not_repro)}/{n} = {len(not_repro)/n*100:.1f}%")
    print("  Non-reproduction breakdown:")
    for label, cnt in buckets.items():
        print(f"    {label}: {cnt}")

    GEN.mkdir(parents=True, exist_ok=True)
    def tex_label(lbl: str) -> str:
        return lbl.replace("_", r"\_")
    rows = "\n".join(
        rf"\quad {tex_label(label)} & {cnt} & {cnt/len(not_repro)*100:.1f}\% \\"
        for label, cnt in buckets.items()
    )
    tex = rf"""% Auto-generated by analysis/rq2_reproducibility.py -- do not edit by hand.
\begin{{table}}[t]
\centering
\begin{{tabular}}{{l c c}}
\toprule
\textbf{{Technique / outcome}} & \textbf{{Count}} & \textbf{{Rate}} \\
\midrule
Reproduced by Shaker (25 stress runs) & {shaker.k}/{n} & {shaker.rate*100:.1f}\% \\
Reproduced by ReRun (100 re-executions) & {rerun.k}/{n} & {rerun.rate*100:.1f}\% \\
Reproduced by \emph{{either}} technique & {either.k}/{n} & {either.rate*100:.1f}\% \\
\midrule
\multicolumn{{3}}{{l}}{{\emph{{Not reproduced by either ({len(not_repro)}/{n}), by reason:}}}} \\
{rows}
\bottomrule
\end{{tabular}}
\caption{{Reproducibility of the {n} ground-truth flaky tests on independent
hardware, with the reason each non-reproduced test yielded no verdict flip.}}
\label{{tab:rq2_repro}}
\end{{table}}
"""
    (GEN / "tab_rq2_repro.tex").write_text(tex)
    print(f"\nwrote {GEN / 'tab_rq2_repro.tex'}")


if __name__ == "__main__":
    main()
