#!/usr/bin/env python3
"""
RQ3: Which test/project characteristics distinguish tests whose flakiness
reproduces (detected by either technique) from those that do not?

- Categorical: manual flakiness category (100NOD subset) -> distribution and
  detection rate per category (the key qualitative point: the sample is
  dominated by network/random flakiness, which resource-stress cannot amplify).
- Numeric project traits (from analysis.fetch_metadata): project size (LOC,
  #files), #test files, #declared deps -> Mann-Whitney U + Cliff's delta,
  detected vs. not-detected groups.
- Fisher's exact on a coarse categorical split when cell counts allow.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
from scipy import stats

from analysis.load import load_paired
from analysis.stats_util import cliffs_delta

GEN = Path(__file__).resolve().parent.parent / "paper" / "generated"
NUMERIC = [("loc", "Project size (LOC)"), ("n_files", "\\# files"),
           ("n_test_files", "\\# test files"), ("n_deps", "\\# dependencies")]


def category_breakdown(df):
    sub = df[df.category.notna()].copy()
    print(f"\n=== RQ3 flakiness categories (n={len(sub)} with a manual label) ===")
    rows = []
    for cat, g in sub.groupby("category"):
        det = int(g.either_flaky.sum())
        rows.append((cat, len(g), det, det / len(g) * 100))
    rows.sort(key=lambda r: -r[1])
    for cat, tot, det, rate in rows:
        print(f"  {cat:<22} n={tot:<3} reproduced={det:<3} ({rate:.0f}%)")
    return sub, rows


def numeric_tests(df):
    have = df[df.get("loc").notna()] if "loc" in df.columns else df.iloc[0:0]
    print(f"\n=== RQ3 numeric traits (n={len(have)} with fetched metadata) ===")
    results = []
    for col, label in NUMERIC:
        if col not in have.columns:
            continue
        det = pd.to_numeric(have.loc[have.either_flaky, col], errors="coerce").dropna()
        mis = pd.to_numeric(have.loc[~have.either_flaky, col], errors="coerce").dropna()
        if len(det) < 3 or len(mis) < 3:
            continue
        u, p = stats.mannwhitneyu(det, mis, alternative="two-sided")
        d, mag = cliffs_delta(det, mis)
        results.append((label, det.median(), mis.median(), p, d, mag))
        print(f"  {label:<22} med(det)={det.median():.0f} med(miss)={mis.median():.0f} "
              f"p={p:.3f} delta={d:+.2f} ({mag})")
    return results


def emit_tex(cat_rows, num_rows, n_cat, n_num):
    GEN.mkdir(parents=True, exist_ok=True)
    cat_tex = "\n".join(
        rf"{cat} & {tot} & {det} & {rate:.0f}\% \\" for cat, tot, det, rate in cat_rows)
    num_tex = "\n".join(
        rf"{label} & {md:.0f} & {mm:.0f} & {p:.2f} & {d:+.2f} ({mag}) \\"
        for label, md, mm, p, d, mag in num_rows) or r"\multicolumn{5}{c}{(metadata unavailable)} \\"
    tex = rf"""% Auto-generated by analysis/rq3_characteristics.py -- do not edit by hand.
\begin{{table}}[t]
\centering
\small
\textbf{{(a) Reproduction by manual flakiness category}} ($n={n_cat}$ labelled)\\[2pt]
\begin{{tabular}}{{l c c c}}
\toprule
\textbf{{Category}} & \textbf{{Tests}} & \textbf{{Reproduced}} & \textbf{{Rate}} \\
\midrule
{cat_tex}
\bottomrule
\end{{tabular}}

\vspace{{6pt}}
\textbf{{(b) Project traits: reproduced vs.\ not}} ($n={n_num}$ with metadata)\\[2pt]
\begin{{tabular}}{{l c c c c}}
\toprule
\textbf{{Trait}} & \textbf{{Med.\ repro}} & \textbf{{Med.\ not}} & \textbf{{$p$}} & \textbf{{Cliff's $\delta$}} \\
\midrule
{num_tex}
\bottomrule
\end{{tabular}}
\caption{{Reproduced versus non-reproduced flaky tests: (a)~reproduction by
manual flakiness category; (b)~project traits compared with the Mann--Whitney U
test and Cliff's~$\delta$.}}
\label{{tab:rq3_traits}}
\end{{table}}
"""
    (GEN / "tab_rq3_traits.tex").write_text(tex)
    print(f"\nwrote {GEN / 'tab_rq3_traits.tex'}")


def main():
    df = load_paired()
    sub, cat_rows = category_breakdown(df)
    num_rows = numeric_tests(df)
    emit_tex(cat_rows, num_rows, len(sub), int(df.get("loc").notna().sum()) if "loc" in df.columns else 0)


if __name__ == "__main__":
    main()
